/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5 at Mon Sep 05 18:05:50 2016. */

#include "ThesisProtocol.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ReceivedMessage_fields[8] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ReceivedMessage, deviceX, deviceX, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, ReceivedMessage, deviceY, deviceX, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, ReceivedMessage, deviceVoltage, deviceY, 0),
    PB_FIELD(  4, BOOL    , OPTIONAL, STATIC  , OTHER, ReceivedMessage, lastPost, deviceVoltage, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, ReceivedMessage, submitTime, lastPost, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, ReceivedMessage, wifiTime, submitTime, 0),
    PB_FIELD(  7, MESSAGE , REPEATED, CALLBACK, OTHER, ReceivedMessage, devices, wifiTime, &ReceivedMessage_Device_fields),
    PB_LAST_FIELD
};

const pb_field_t ReceivedMessage_Device_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, ReceivedMessage_Device, mac, mac, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, ReceivedMessage_Device, datapoints, mac, &ReceivedMessage_DataPoint_fields),
    PB_LAST_FIELD
};

const pb_field_t ReceivedMessage_DataPoint_fields[3] = {
    PB_FIELD(  1, SINT32  , REQUIRED, STATIC  , FIRST, ReceivedMessage_DataPoint, rssi, rssi, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, ReceivedMessage_DataPoint, secondsSince, rssi, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ReceivedMessage, devices) < 65536 && pb_membersize(ReceivedMessage_Device, datapoints) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ReceivedMessage_ReceivedMessage_Device_ReceivedMessage_DataPoint)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ReceivedMessage, devices) < 256 && pb_membersize(ReceivedMessage_Device, datapoints) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ReceivedMessage_ReceivedMessage_Device_ReceivedMessage_DataPoint)
#endif


/* @@protoc_insertion_point(eof) */
